"""empty message

Revision ID: 0beeb66aaf81
Revises: 207f674db186
Create Date: 2022-06-07 19:19:28.744708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0beeb66aaf81'
down_revision = '207f674db186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE todo SET completed = False WHERE completed IS NULL;')
    
    op.alter_column('todo', 'completed', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
